name: HMRC on GitHub

permalink: /:title/

sass:
    sass_dir: _scss

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

category-list: 
    - Development Documentation
    - The HMRC Tax Platform
